version: '3.1'
services:
  stats-client:
    build: stats/stats-client
    image: stats-client-image
    container_name: stats-client-container
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9000

  stats-server:
    build: stats/stats-service
    image: stats-service-image
    container_name: stats-service-container
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot


#  ewm-main-service:
#    ports:
#      - "8080:8080"


#  ewm-db:
#    image: postgres:14-alpine
